### ISSUE TITLE
UI glitch in Safari 

### ISSUE THREAD

**Issue by cshopeorg** [cshopeorg/cshopeorg.github.io#1]
![image](https://user-images.githubusercontent.com/43283022/46046616-bdde9d80-c0ef-11e8-9da1-544f7895ad99.png)

Similarly, check and fix needed for other major browsers.

**Comment by cshopeorg** [comment]
The issue is the background green color. It should actually look like the below image. 
![image](https://user-images.githubusercontent.com/43283022/46046721-1c0b8080-c0f0-11e8-9865-ee31de97b6d0.png)

**Comment by Laksh47** [comment]
The green background exists in chrome too!

```
.cd-timeline__img.cd-timeline__img--picture {
    background: #75ce66;
}
```

But chrome has resized/stretched the image to fit the parent div (hence hiding the green background)

**Comment by cshopeorg** [comment]
Yea. My bad in description. Actually what I want is the image to be stretched to the parent div like how it is displayed in Chrome. 
So ideally, whatever the color, It shouldn't be visible.

**Comment by cshopeorg** [comment]
fixed.
